name: Deploy Documentation
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  DeployDocs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: 'Install Swift Toolchain'
        uses: finnvoor/swiftly-action@main
      - name: 'Install Playdate SDK'
        uses: finnvoor/playdatesdk-action@main
      - name: Select Xcode
        run: |
          sudo xcode-select -s '/Applications/Xcode_16.4.app'
      - name: Build
        run: |
          xcodebuild docbuild -scheme PlaydateUIKit \
            -configuration Release \
            -derivedDataPath /tmp/docc \
            -destination 'platform=macOS' \
            -toolchain "swift latest";
          $(xcrun -f docc -toolchain "swift latest") process-archive \
            transform-for-static-hosting $(find /tmp/docc -type d -name 'PlaydateUIKit.doccarchive') \
            --hosting-base-path . \
            --output-path docs;
          echo "<script>window.location.href += \"/documentation/playdateuikit\"</script>" > docs/index.html;
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4